version: "3"
services:
  postgres:
    image: "postgres:15"
    container_name: "my_postgres"
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
  grafana:
    image: docker.io/grafana/grafana-oss:11.1.0
    container_name: my_grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
volumes:
  my_dbdata:
  grafana-data:
    driver: local